### ISSUE TITLE
[cosmetic] Message when trying to apply locked paints is different (wrong?)

### ISSUE THREAD

**Issue by idlehands95** [nlgxzef/NFSMWUnlimiter#9]
Right after installing the mod, the message when you try to apply paint that is locked is different from the one that is supposed to be shown.
For example, when trying to apply metallic paint in "My Cars" right at the beginning of the game (career not started), the message is usually "Unlock these paints by beating Sonny...", but after installing the mod the line says "The car is locked".

**Comment by YlayaQueen** [comment]
It's should be to fixed

**Comment by YlayaQueen** [comment]
I had the same "The car is locked"
